"""Deterministic compressed payloads for authoritative model JSON files."""

from __future__ import annotations

import base64
import zlib

AUTHORITATIVE_JSON_PAYLOADS = {
    'assets/blindboxchallenge/models/block/anywhere_door.json': 'eNqdkMsKgzAQRfeC/yDpVqgu6sJfKaXEOFZpzJQ80CL+exMfNS3d1Gxy5w7nDjNDGEQRoW3RgNDIGDeqQUHyqKJcQTx1NfTaSFDWHZzhAM5tRQreiLLAntXWAHGDvODI7kcqnl0NEq4loiSOGeco4NDaQS7qPEctibZXSWw337003nTi6WyVl7dJNH6xJw9IM79IfuAVZf6Ck1diJz6t7Rhu+4O7wtYcvRnEPPaSAqWu98IKzX64A6X3skD/Y1e5iOm7hMEYBi8HoosN',
    'assets/blindboxchallenge/models/block/bml_cheer_stick_off.json': 'eNoti00KhSAQgPeCd5BZB2/fZUSnMaVJY5oHQXT3Mtp+P6c1zsEWhKrC6GAtlVBC0jFyw+WnTTDD8FZKh/6F9qc7O+jo1c8XudQptgNzYKY60/fHlT1mIvG7Flx8Swn6e1lzWXMD1YAn5Q==',
    'assets/blindboxchallenge/models/block/bml_cheer_stick_on.json': 'eNoti0sKhDAMQPeF3qFkPeDey5Q2E20xpkPMgCDeXStu3+fwLgT4JSUxGAOsVQg1TTZmbrgM1hQLfJ7KaLe/0nZ3RwcdPfr+Mlf55rZjScwkM71/XjliIdK4WcUlNoG+nt6d3l2rOieH',
    'assets/blindboxchallenge/models/block/bml_cheer_stick_wall_off.json': 'eNotjEEKxCAMRfeCd5CsC7PvZUTTOEpTHdIMUyi9e7XM9v33/mmNc/AJQlVhdrCVSigh6Ry54fr6BWavTTDD9KhKh36F9i6fAwz0zD2OXOoS24G5V1Tf9D+JG3vMROJ3Lbj6lhKM9rLmsuYG0NUp9A==',
    'assets/blindboxchallenge/models/block/bml_cheer_stick_wall_on.json': 'eNotjEEKwzAMBO8G/8HoHOg9nzG2qtYmihwUlQZC/l479Do7s6d3IcCWlMRgDrBWIdT0sjlzw+XxTczRmmKB6VaNDvso7V0+BxjonnucucoztwNLr0je9D/JK0csRBp3q7jEJjDSy7vLux+kgCmW',
    'assets/blindboxchallenge/models/block/diamond_pillow.json': 'eNrtks0KwjAQhO+FvkOJV8EfFMVXEZEk3Wpwmy1NSgXpu9toa6OoKD0J5pJhwjdLkjmFQRQxngoF2pKUWBhFmq2ihKOB4eXUwtEWOZjaPTmjthIuciVrgwlUOhZ0lHuOCHoHK4EkD6NY8ZR0vM0UIpXMcdU1DhDSepiLW1/jmlSXm1Pa+W5Nhp0ee3rSys3NZJYe2LkHLHx4/oROuPTvePFiKvW91b2Hu/2geYjuvPLGsCLrAWvK7b4Hb6joxZdgbA8c+Nd4KxvRxr2rx/TFD08/qcfMA5Z+PWb/evxAPdy2CYMqDM5JC/24',
    'assets/blindboxchallenge/models/block/glow_stick.json': 'eNoti0sKgCAQQPeCd5BZB+29TOg0lTRp2ERCdPc02r7PrZUxsLtMUcAa2EIkzG4S6znh2kvKuED3VUJFzkxH7e4GGvp0/TyHOPpUcHHMFGf6/5nTNRwScIW2PFo9Wr1mPyRj',
    'assets/blindboxchallenge/models/block/glow_stick_wall.json': 'eNotjEEKgCAQRfeCd5BZB+27TOg0lTRp6IRBdPc02r7/3r+1MgYOmygIDAZ2HwiTnWVwHHHri2UeJSZcoftUoUvORLnKdwMNfXONHfswuXjhWisKC/0nC8cyZvG4QUserR6tXk8NJnI=',
    'assets/blindboxchallenge/models/block/music_box.json': 'eNotjEEKgCAQRfeCd5BZB+27jOg0lTRamIIQ3b0x2r73/r+1MgZOlykVmAzEkAizW8rk+cB9xOrJOmYYvrBQKzXTJendgaAuZeg5pNkfDTcBlFb6D2K9AloR0PtHq0erF2VEJCY=',
    'assets/blindboxchallenge/models/block/safety_landing.json': 'eNotjEEKgDAMBO+F/qHkLHj3MyWtUYsxSo2giH+3Fa+zM3tb4xxsmEkUOgdLEooZB+0Cr3Fu4xHIIzM0n6h06pFpL+pdQUF1LGHgJH1YzzgVQDLSf7DjQHp5RumTjFCjx5rHmhcteiYl',
    'assets/blindboxchallenge/models/block/stone_pillow.json': 'eNrtksEKwjAQRO+F/kOJV0EtiuKviEgStxrcZqVJqVD67zba2igqSk+CuWSY8GZJMmUYRBHjqVCgLUmJuVGk2TJKOBoYXk4tnGyegand0hm1lXCRKVkbTKDSW0EnueeIoHewFEjyMDKWNGyOCpEK5qjqGgYIaT3Kha2uYU2mS80o7Xy3JsNOjz09aeX6ZjJLD+zMA+Y+PHtCJ1z6N7x4Wyr0vdW9hrv7oHmG7rzyxrD82APWlNl9D95Q3osvwNgeOPCv8VY2oo17V4/4xQ/Hn9Rj6gELvx7Tfz1+oB5uW4dBFQZn9979BQ==',
    'assets/blindboxchallenge/models/item/adrenaline.json': 'eNoljEEKwzAMBO8G/8HoXEjP/o1ibxODowRVAZeQv9dur7Mze3kXAh2sEKMYaCuCpPyyWAzbtECgbMj0+ImGZqfi3dVrgI4qf6DP0c61SJ73llauFbLg/8G5n3PfQCO5vbu9+wLiCCVE',
    'assets/blindboxchallenge/models/item/anywhere_door.json': 'eNqr5uVSUFAqSCxKzStRslJQSsrJzEtJyq9IzkjMyUnNS0+1SsrJT87WT8yrLM9ILUqNT8nPL1Li5arl5QIASQ8TyQ==',
    'assets/blindboxchallenge/models/item/bath_bucket.json': 'eNoljMEKgzAQBe+B/EPYc6Ge/RnZxKeGxrVsV1DEf9fY6zAzh3ch0JcVYtQGmrMgKQ/WZsP8HiFQNvT0ekTDZqvid6tHBTcqvEOb2saSpY/LliYuBTLi/4hsUxfX9IFRbU7vTu8uCnElrQ==',
    'assets/blindboxchallenge/models/item/beef_bites.json': 'eNoljEEKgzAQRfeB3CHMutCuvYxM4lcDcSyTKVjEuzepu8/jvX96FwK9WSFGQ6AtC5LybEM2bM8FAmXDRI+/aDjso6hNPTtoqPAX+uptLFmmuB9p5VIgC+6PCMxjbLNSTy7vLu9+4P0lOQ==',
    'assets/blindboxchallenge/models/item/birthday_candle.json': 'eNoljMEKgzAQBe+B/EPYc6E9+zNlk7xqYF1luwVF/Pea9jrMzBFDSrSyQZ2GRHNTFOOXD80x30cojB2Vbj/RsfnH8L7Uo4MLCe+wR2+zNK152crEItAR/0du5lPl/VlYq4B6d8ZwxvAFsUcnTg==',
    'assets/blindboxchallenge/models/item/black_knight_telescopic_knife.json': 'eNqdjssKgzAURPeC/xCyLq3d+iulSExGDcZErmmxiP/ePPpYdNfVhWHumbOVBWN8FgTrec34pC0kic7X2mM69bAg4aH4IRU9Vn8jLKG6xSBERjxAVfxtjbaqdaschDGwPTKjNUKOzWh1P/jGw2CRbtYyJh14pOwZ7u4g0irRL5n+GomKBKVlUPlOp/x3NCjCqqBcs/OxelfzRnqZnIL5V7j54DNvj+daFntZPAGvqGV0',
    'assets/blindboxchallenge/models/item/black_knight_telescopic_knife_extended.json': 'eNoljUEKwyAQRfeCdwiuC+06l5FRf4xkMglmCikhd6+228f771/WDIPbqULUjYNbiyBWmnQsivWZIaikSO7xExWnviuOpl4dNMT0QX31beAiKWxnnIkZkvFvBKa4+EVKntUrGEfc9hI7meBbEJLaQc/d1tzWfAHr6jC4',
    'assets/blindboxchallenge/models/item/black_truffle_ham_cracker.json': 'eNoljUEKwyAQRfeCdxDXhXady8hovolktGU6gZSQu1fb7eP9909rnPMvEjT1k/O1NCShrFNR1PuCBiHF7G8/UXHoLnh39RygI6YP5DG2kUub4/NIKzGjLfg3IlPagsqeMyOsVEM/SBvEj8JlzWXNF2vHK1Q=',
    'assets/blindboxchallenge/models/item/blind_box.json': 'eNolzMEKgzAQhOF7IO8Q9lywZ19GNnGaBuJatltQxHc3sdePf+bwLgT6sEKMxkBLESTll43FsAwZAmXDTI87NGz2U3xbenRoVHmHPvs21iJzXLf05lohGf+Pm6fm1Bend6d3F7otJOI=',
    'assets/blindboxchallenge/models/item/bml_cheer_stick.json': 'eNqr5uVSUFAqSCxKzStRslJQSsrJzEtJyq9IzkjMyUnNS0+1SsrJT87WT8rNiU/OSE0tii8uyUzOjs9PS1Pi5arl5QIAzm0WCw==',
    'assets/blindboxchallenge/models/item/cat_doll.json': 'eNoljMEKgzAQBe+B/EPYc6E9+zNlTV41sK5lXcEi/rvGXoeZ2WNIib5sUKcu0VQV2fjjXXVMzwEKY0ehxy06Nl8Ny6XuDVxI+Ad7tbaXqqWftzyyCHTA/5HZ32UWoRYcMRwxnJIaJHM=',
    'assets/blindboxchallenge/models/item/chainsaw_sword.json': 'eNoljEEKgzAQRfeB3CHMulDXXqaM5msDcSyTKVrEuzfR5X+89w/vQqAPK8SoD7Qkwag8WZ8My3OGQNkQ6XGJht2+ilLVo4GKMv+gXWuHnCQO6z6+OWfIjPujziSFt1fZVo3UstO707s/iP8nDQ==',
    'assets/blindboxchallenge/models/item/clockwork_chicken.json': 'eNoljMEKgzAQBe+B/EPYs9Ce/RmJ66uGxE3ZbqlF/HdNex1mZvcuBHpGhRj1gdYkYI0P65Nhvc0QaDRM1P1Ew2ZvxetS9wYuVOIXem/tWJJMY914iaVAZvwfXCrnT9U88JI4Q6iVh3eHdycIjCg0',
    'assets/blindboxchallenge/models/item/death_note.json': 'eNoljMEKgzAQBe+B/EPYs9Ce/RlZzasGko2sK1jEf6+p12FmTu9CoJUVYtQHKkkwKX+sT4bymiFQNkTq/qLhsF2x3erZwI0yf6Hv1o45SRzrMS2cM2TG84hgWwapBmrJ5d3l3Q/iYCVM',
    'assets/blindboxchallenge/models/item/decision_coin.json': 'eNoljMEKgzAQBe+B/EPYc6E9+zNlTV51IW7KugWL+O819TrMzB5DSvRmgzoNiRZRZOOXD+JY7hMUxo5Ct7/o2PxjWE917+BElb+wR2/HKlrGtuWZa4VOuB4FWVZp+sxNlHp1xHDE8ANdcSaH',
    'assets/blindboxchallenge/models/item/deep_sea_fish.json': 'eNoljMEKhDAMBe+F/kPJeWE9+zMS7VMLNStpFhTx37V6HWbm8C4EWlkhRm2gJQkG5dHaZFi+EwTKhkifRzRs9leUWz0quFHmHdrUts9JYv/bhplzhkx4HxFYuwLuxlRmqtXp3endBVvgJnA=',
    'assets/blindboxchallenge/models/item/diamond_pillow.json': 'eNqr5uVSUFAqSCxKzStRslJQSsrJzEtJyq9IzkjMyUnNS0+1SsrJT87WT8lMzM3PS4kvyMzJyS9X4uWq5eUCAF1mFCU=',
    'assets/blindboxchallenge/models/item/efficient_pig_breeding.json': 'eNoljM0KgzAQBu+BvEPIWWjPvozk50u6ELeybsEivrtJex1m5rTGOb8FAaufnV+JkSQUnUmxPioYEhTZTz9RcehHsHf1HKCjFr6Q52hjI87xfaRXaA1c8X+gFErU/8tGdYkCZOLqR35Zc1lzA+JGKhw=',
    'assets/blindboxchallenge/models/item/eggy_eye_mask.json': 'eNoljMEKgzAQBe+B/EPYc6Ge/RlZ9ZkGk7WsWzCI/17TXoeZOb0Lgd6sEKM+UEmCSXmxPhnKM0KgbJjp8RMNh30U+62eDdwoc4V2rR1zknncjunFOUMi/g/EWAdUDIX3lVp1eXd59wVdziaK',
    'assets/blindboxchallenge/models/item/face_mask.json': 'eNoljMEKgzAQBe+B/EPYc6Ge/RlZ41ODybasW1DEf9fU6zAzh3ch0JcVYtQGKkkQlUdrk6G8JwiUDQO9/qJhs59ivdWjghtl3qFNbfucZOg/W5w5Z8iE5zFyRFd4XagWp3endxe4syTL',
    'assets/blindboxchallenge/models/item/fairy_wand.json': 'eNoljMEKgzAQBe+B/EPYc6E9+zOyMU8bSFbZbqki/rumXoeZ2b0LgRZWiFEXqGbBoDxalw31OUGgbEj0+IuG1b6Kz6XuDVyo8AZ9tTaWLCnO6/DmUiAT7sfIWbf+x5KoJYd3h3cn4zglVQ==',
    'assets/blindboxchallenge/models/item/flowing_black_flag.json': 'eNoljMEKwjAQBe+B/EPIWdBzf6Zs0pcY3G5lXbFS+u9t9DrMzOZdCPFJCrE4hDg3QVYqNjTDfK0QKBmmePmJhtXeitepbh2ciOkLvfU2cZMpLWu+EzOk4v8ovHya1DEx5cdYmGrs6e7d7t0BMgUofA==',
    'assets/blindboxchallenge/models/item/glow_stick.json': 'eNqr5uVSUFAqSCxKzStRslJQSsrJzEtJyq9IzkjMyUnNS0+1SsrJT87WT8/JL48vLslMzlbi5arl5QIACfsSiQ==',
    'assets/blindboxchallenge/models/item/green_soy_milk.json': 'eNotjMEKg0AMBe8L+w9LzoX27M9I1Fe7mI0lpqCI/65bvA4zs8eQEn3ZoE5NopIVvfHbm+wozxEKY8dAj7/oWP1nWC51r+BCwhvsVdtOsg7dvPYfFoGOuB8GaLvMW1uyTFSzI4YjhhOJIycI',
    'assets/blindboxchallenge/models/item/ham_sausage.json': 'eNoljMEKgzAQBe+B/EPYc8Ge/Zmy6msMJNuyWUER/12j12Fmdu9CoD8rxKgPVJJgVP5anwylixAoGyZ63aJhtUVRL3Vv4EKZN+i7tUNOMg2/dZw5Z0jE85i5fCovlSOoNYd3h3cnCt8lrw==',
    'assets/blindboxchallenge/models/item/headphones.json': 'eNoljMEKgCAQBe+C/yCegzr3N1u+UrAttg2K6N/Tug4zc1vjnN9IwOp755fEGIUm7ZNiaWcwhBTBN5+oOPUQ7EW9Kygo0wXpajvkxGFYzzFSzuAZ/yOCwhZXLlVNHmsea17ikiVQ',
    'assets/blindboxchallenge/models/item/kazoo.json': 'eNolzEsKhDAQhOF9IHcIvR7QtbdptdRg7EhPCz7w7pqZ7c9XdXkXAq2sEKMm0BIFnfJgTTQs1QiBsqGnzw8adtsU35deJbwp8QGty7ZNUfo2793EKUFG/D9mPnOmom/vbu8eHwMjVQ==',
    'assets/blindboxchallenge/models/item/letter.json': 'eNolzMEKgzAQhOF7IO8Q9lyw57zNGqcaWFfZrmAR371Je/35Zq4YUqKdDeqUE61VUYxfnqtjHWYojB0TPX7QcfpheDd69dCS8Af27NtRqk7jdpaFRaAz/h8Cdxh1fsdwx/AFRcojwQ==',
    'assets/blindboxchallenge/models/item/lighter.json': 'eNolzMEKgzAQhOF7IO8Q9lyoZ99mjdMYWLdluwWL+O4mev35ZvYYUqIPG9RpTLRWRTZ++Vgd67NAYeyY6XFBx+Y/w7fRvYeWhP+woW8nqTpP7y0vLAItuD+klsVh1P0RwxHDCWwrJCA=',
    'assets/blindboxchallenge/models/item/long_screwdriver.json': 'eNoljMEKwjAQBe+B/EPYs6Dn/oxsk2cMbLeyXbVS+u82eh1mZoshJXqwQZ2GRFNTZOObD80xnSsUxo5Cp5/oWP1pWA516+BAwh/YpbejNC3jvOY7i0Ar/g+ZtV6XbHgXay8Y9XCPYY/hC9+XJ/A=',
    'assets/blindboxchallenge/models/item/magic_crispy_noodles.json': 'eNoljMEKwyAQBe+C/yCeC+05PxM2+moFXcNmCwkh/x5tr8PMnNY451cSsPrJ+ZoZQeitU1bUZwJDSBH94ycqdv0Ktq6eA3RU6IC8RruUzHFpe/hQKeCE/6NSymEOkrf1mLm1WHo/4suay5objC8pfg==',
    'assets/blindboxchallenge/models/item/math_exam_paper.json': 'eNoljMEKgzAQBe+B/EPYc6Ge/RlZ9amBZBu2W0gR/12j12Fmdu9CoMIKMeoD5SiYlBfroyG/VwiUDTO9btFQ7af4XurewIUS/6Fda8cUZR4/ddo4JciK55HZtgGV81C4QKl1h3eHdyex2idc',
    'assets/blindboxchallenge/models/item/million_pound_note.json': 'eNoljMEKgzAQBe+B/EPYc6E9+zOymlcb2Gxku4JF/Pea9jrMzBFDSrSyQZ2GRLUoZuOnD8VR7wsUxo5Mt5/o2H0zvC/16OBCwh/Yo7eTFM1T2+cXi0AX/B+1iJSm49o2zaM2B/X0jOGM4Qs2dCi/',
    'assets/blindboxchallenge/models/item/music_box.json': 'eNqr5uVSUFAqSCxKzStRslJQSsrJzEtJyq9IzkjMyUnNS0+1SsrJT87Wzy0tzkyOB0oo8XLV8nIBAPWXEhw=',
    'assets/blindboxchallenge/models/item/nail_art.json': 'eNoljMEKhDAMBe+F/kPJWVjP/oxEfWohRokRXMR/X7teh5m5YkiJNjaoU5NoyYreePQmO5bPBIWxY6DqLzpOPwz7o14FPEj4C6tL20nWoVvPfmYR6IT3oZylZXMqwR3DHcMPkp8kew==',
    'assets/blindboxchallenge/models/item/oil_chestnut.json': 'eNoljMEKhDAMBe+F/kPJeWE9+zMS61MLMS4xgov472vX6zAzZwwp0YcN6tQmWooiG4/eFsfynqAwdgz0+ouOw3fDdqtnBTcS/sKa2vZSdOjXI88sAp3wPNYiXZ6xue5ONbpiuGL4ATYmJkI=',
    'assets/blindboxchallenge/models/item/packing_tool.json': 'eNoljMEKwjAQBe+B/EPYs6Dn/oxs02cMbjdlXaFS+u9t9DrMzBZDSrSwQZ2GRHNVZOOHD9UxXwsUxo6JLj/RsfrH8D7VrYMTCX9ht96OUnUa25qfLAIt+D8Wzq+q5e6tCfVoj2GP4QA04CYr',
    'assets/blindboxchallenge/models/item/paper_cup.json': 'eNoljMEKhDAMBe+F/kPJWVjP/ozE+tRCjSVGcBH/fe16HWbm8i4EKqwQoy7QmgRRebIuGdbPDIGyYaTmLxpOOxT7o14VPCjzF9rWdshJxmE748I5Q2a8j8IF2sejUC1u727vfrs1JPA=',
    'assets/blindboxchallenge/models/item/pickaxe_hoe.json': 'eNoljMEKgzAQBe+B/EPYs2DP+ZmyxlcNjausK6SI/17TXoeZOb0LgTZWiFEMtGRBUn5ZzIalnyBQNozU/URDtUOx3+rZwI0Kf6CP1g4lyzisNc1cCmTC/7Hl9OaK57yCWnN5d3n3BQs0JbE=',
    'assets/blindboxchallenge/models/item/pink_butterfly_wings.json': 'eNoljMEKgzAQBe+B/EPYs2DP/oxs9JmGxq2sK1XEf69pr8PMnN6FQAsrxKgLNGfBoDxZlw1zmyBQNozU/ETDbptivdWzghsVPqCP2saSZYzvfXhyKZCE/2PJ8urjZgadytF/sqSVanx5d3n3BZB4Kao=',
    'assets/blindboxchallenge/models/item/potato_chips.json': 'eNoljMEKgzAQBe+B/EPYc6Ge/ZmyxqcG4iasW7CI/66x12FmDu9CoMoKMeoDrUkQlSfrk2F9zxAoG0Z6PaJht69iu9WjgRtl/kG71g45yTiUPS6cM2TG/1GLsZVPXFLdqEWnd6d3FzalJj4=',
    'assets/blindboxchallenge/models/item/potato_snack.json': 'eNoljMEKgzAQBe+B/EPYs1DP/oys8WlD40bWLSjiv9fY6zAzp3ch0MoKMeoCLUkQlSfrkmF5zRAoG0ZqHtGw21ex3epZwY0yH9C2tkNOMg5lj2/OGTLj/1iLsZV+E44fqtHl3eXdDzaGJjc=',
    'assets/blindboxchallenge/models/item/purple_toy_pickaxe_sword.json': 'eNqdjs0OgjAQhO8kvAPp2SheeRVjSG0HbOwPWYpCCO9ufyQevHnZzU5m55u1LKqKDZxgPWsqZpSFIN75RnmYUw8L4h6SHZLRY/YTYQzWNQpB0nwB1fH3ppWVNzeLO9catkfOGCYaNFrvlnZQ4sFntOPLkdwvFoO2nO+eIFIyAS4Z8OHElgSpRGjzpSf9l5vzO0cmWM/HejdnSnoyTkL/0zpNlnO2uK5lsZXFGymoZSM=',
    'assets/blindboxchallenge/models/item/purple_toy_pickaxe_sword_sword.json': 'eNoljEEKwyAURPeCdxDXhXady8iPTlOpUfn5oYaQuyc2m1k83rxdK2NsJUYWOxg7xwzP9JYhCubnhAwmQbCPvyhosjKWS907uFCiDfzq3zHFHMbS/IdSQp5wN+rKNcFJ2VyN/ksNbvkVDvfanjm0OrQ6AWdQLeQ=',
    'assets/blindboxchallenge/models/item/quail_egg.json': 'eNoljMEKg0AMBe8L+w9LzoV69mdK1Od2IaY1RrCI/15Xr8PM7DGkRF82qFObaCqK3nj0tjimZ4bC2DHQ4xIdm6+G5VT3Ck4k/IM1te2k6NB9tv7NItCM+zGvXOSFnKkWRwxHDH+6lSTf',
    'assets/blindboxchallenge/models/item/rainbow_hoop.json': 'eNoljMEKgzAQBe+B/EPYs9Ce/RnZ6KsG4kbWLSriv9fU6zAzp3ch0MIKMWoDzUnQK3+sTYb5NUKgbBio+YuG3b6K9VbPCm6U+YC+axtzkiGWvZ84Z8iI56GcJJatm0pZqEaXd5d3PzXhJjg=',
    'assets/blindboxchallenge/models/item/rat_jerky_totem.json': 'eNoljEEKhDAQBO+B/CHMeWE9+xkZtdW4cVxmZ0ER/26ixy6q+vAuBPqyQozqQEsUdMqD1dGwvEcIlA09vW7RsNlf8cvqUUBGiXdoVdo2RenbdesmTgky4vnIfTNDP3tja95UutO707sLtKsnhA==',
    'assets/blindboxchallenge/models/item/ration_pack.json': 'eNoljMEKgzAQBe+B/EPYc8Ge/RlZ46sNxlW2Kyjiv5vY6zAzp3ch0MoKMWoDzUkQlT/WJsPcjBAoGwZ6PaJht03xK+pZQUGZD+i7tn1OMvTLHr+cM2TE/1H6tEi3cpyoNpd3l3c3DCElvA==',
    'assets/blindboxchallenge/models/item/returning_scissors.json': 'eNoljMEKwjAQBe+B/EPYs6Dn/oxs02cMpFvZXaFS+u8meh1m5oghJXqxQpymRGsVZOWHT9WxXgsEyo6FLj/RsftbYV09Buio8Qd6G+3cqizztucntwYp+D8UPZEq5W65mm1qNNIzhjOGLzl8KOc=',
    'assets/blindboxchallenge/models/item/road_barrier_helmet.json': 'eNoljMEKgzAQBe+B/EPYc6E9+zOyMa8a2KxluwWL+O+a9jrMzB5DSvRigzoNiVpVTMZPH6qj3WcojB2Fbj/RsfnH8L7UvYMLCX9hj95mqVryuk0Li0Bn/B+2chkzm1XYuEAanHp7xHDEcAJeSCj7',
    'assets/blindboxchallenge/models/item/safety_exit_sign_shield.json': 'eNoljMEKgzAQBe+B/EPIudCe/ZmwmmdciKskW4iI/65pr8PMnNY453cqEPWD8ysLpkKzDqxY3wmCQoroXz9R0fRbUB/17OBBmQ6UT2/HzBLHrU0L5QxJ+D8qzdAjoLGGyklCXRg5+t5f1lzW3BXBKr4=',
    'assets/blindboxchallenge/models/item/safety_landing.json': 'eNqr5uVSUFAqSCxKzStRslJQSsrJzEtJyq9IzkjMyUnNS0+1SsrJT87WL05MSy2pjM9JzEvJzEtX4uWq5eUCAF3EFBs=',
    'assets/blindboxchallenge/models/item/sesame_rice_noodles.json': 'eNoljMEKwyAQBe+C/yCeC+05PxM2+poKuoZ1Cykh/x5trsPMHNY45zcSsPrJ+ZIYQeitU1KU5wqGkCL6x19U7PoVtK4eA3SU6Qd5jXbJieNS9/ChnMEr7kdDo4JZUsDMtcbc89Ge1pzWXF9YKQQ=',
    'assets/blindboxchallenge/models/item/shark_dagger_pillow.json': 'eNoljMEKgzAQBe+B/EPYc8Ge/RlZzWsMXaOsK7WI/65pr8PMHN6FQAsrilEbaMoFg/LL2myYmoQCZUOkx0807LYp1ls9KriR8Bf6rG0vucR+3oeRRVAS/o91ZH13kVOCdksWmT9U29O707sLXwcpCQ==',
    'assets/blindboxchallenge/models/item/stone_pillow.json': 'eNqr5uVSUFAqSCxKzStRslJQSsrJzEtJyq9IzkjMyUnNS0+1SsrJT87WLy7Jz0uNL8jMyckvV+LlquXlAgA0iBNy',
    'assets/blindboxchallenge/models/item/sun_candy.json': 'eNoljMEKhDAMBe+F/kPJeWE9+zMS26cWanaJERTx37V6HWbm8C4E+rNCjNpAcxZE5cHabJi/IwTKhkSfRzRstiqWWz0quFHhHdrUti9ZUv/b4sSlQEa8j2WVLrKknWpxend6dwG7uiT1',
    'assets/blindboxchallenge/models/item/sweet_sour_turkey_noodles.json': 'eNoljMEKwyAQBe+C/yCeC+05PyOb+JpKzVrWDU0I+fdoex1m5rDGOf8hAasfnF8SYxJ66pAUy30GQ0gR/e0nKjZdBbWpRwcNZdohj96OOXEcyza9KGfwjP+jfgENtawSWvvGHriUmNukH05rTmsueM4r1w==',
    'assets/blindboxchallenge/models/item/toy_car.json': 'eNolzMEKgzAQhOF7IO8Q9iy0Z19G1jjVQLLKugVFfPcm9frzzVzehUAbK8SoD1SSICp/rE+G8pohUDZM1P2h4bCvYq/0aqGmzCf03bZjTjKN6xEXzhky4/mw9RwiKzV/e3d79wNsmCQi',
    'assets/blindboxchallenge/models/item/toy_knife.json': 'eNoljMEKgzAQBe+B/EPYs9Ce/RlZ9RlDk03ZbkER/13TXoeZObwLgd6sEKM+UEmCSXmxPhnKI0KgbJip+4mGzb6Kz60eDdwo8w59tnbMSeaxbtPKOUMi/g+r+/CStIBacXp3encBvEkk+Q==',
    'assets/blindboxchallenge/models/item/truffle_ham_cracker.json': 'eNoljMEKgzAQBe+B/EPIudCe/RlZ44uGbrZlu4JF/HeT9jrMzOFdCPFNCrE4hFiLICllG4qh3hcIlAxzvP1Ew26b4tPUo4OGmL7QR28nLjJPrz2txAxZ8H+YbjkzxpXq2NbpCY29Pb07vbsAX0Yo+A==',
    'assets/blindboxchallenge/models/item/vodka.json': 'eNolzEEKhDAQRNF9IHcIvR7QtbdpTanB2EpPK4p4d83M9vOqLu9CoJUVYtQEmpOgU+6tSYa5GiBQNkT6/KDhsE3xfelVwpsyn9C6bNucJLbL0Y2cM2TA/2Nf4sRU9O3d7d0DHnUjRg==',
    'assets/blindboxchallenge/models/item/wang_lixin_badge.json': 'eNoljMEKwjAQBe+B/EPIWdBzf6Zsmmdc2K6yrhgp/XcbvQ4zs8WQUn6QQT1PKa+sWIyuPrFjPTcojBw1n36io/vL8DzUbYADCX1gl9EWYa3l3pcbiUAb/o83aZuFO+tcqDbkEe4x7DF8AdwPJ7M=',
    'assets/blindboxchallenge/models/item/wenxu_standee.json': 'eNoljMEKgzAQBe+B/EPYs6Bnf0ZW87SBuC3rSlPEf9fU6zAzh3ch0IcVYtQHWpNgUp6tT4a1XSBQNkRq/qKh2K7YbvWo4EaZf9CutmNOEsd3mV6cM2TB8/hCyj5sxhIBqtXp3endBWEJJqs=',
    'assets/blindboxchallenge/models/item/white_rabbit_candy.json': 'eNoljEEKwzAMBO8G/8HoHGjP+UyQ7W1icNSgqjQh5O+129PCMLOndyHQxgoxGgOtRZCUHzYWw3qbIVA2ZBp+omG3t+LV1LODhiof0HtvYy2S43NPC9cKmfH/+CxtJuUYi02JJR/U08u7y7svMzUokw==',
    'assets/blindboxchallenge/models/item/wind_blown_cake.json': 'eNoljMEKgzAQBe+B/EPYc6E9+zOyia82GNey3aJF/HeTeh1mZvcuBHqzQoy6QHMWJOWnddkw30cIlA0D3f6iYbOv4lPVvYGKCv+gj9bGkmWIy5ZeXApkxPVYK+1jWVbpE0+g1h3eHd6dsjYnVw==',
    'assets/blindboxchallenge/models/item/yijin_manual.json': 'eNoljMEKg0AMBe8L+w9LzoX27M+UqK82JZuWNIIi/rtuex1mZsupFPqww4K6QlUMg/MjOgnU6wSDc2Cky08MLDE7vqe6NXAi5RV+a22vYmP/XoYnq8Im/B+rvMTulW1mpRbtOe05HTXlJjE=',
    'assets/blindboxchallenge/blockstates/anywhere_door.json': 'eNqr5uVSUFAqSyzKTMwrKVayUqgGCQCFEEwgJzc/JTUHKKKUlJOZl5KUX5GckZiTk5qXnmqVlJOfnK2fmFdZnpFalBqfkp9fpATRVwuigEQtLxcAlCAcQA==',
    'assets/blindboxchallenge/blockstates/bml_cheer_stick.json': 'eNqlzE0KgCAQhuF90B3EddBe6Cziz5jipKAWQXT3lIjat5mBB7736DtC6CaSE6FkysjRoBK6MhmBGV6rukQNWIVKdEHLuCsrECHMwCRG5Ue5IFcWIPFcnPI8GkPv9Tl8yiWtf8Ph6bZXz9l3F1rWPNY=',
    'assets/blindboxchallenge/blockstates/bml_cheer_stick_wall.json': 'eNq1k8sKgzAQRfeC/yBZC31s2gp+iyRxosExgSRqi/jvTSjUVSnaZjOBMw8OFzKnSZaRkRpJlbOkyOYAPBKUS9WUQK3LUbpSULSw9v1Er2tATwhDqWqm77yliKAaKBhq3h1YjxVvAUxlneRdNfl2pYUg+fvGw++fL8cVDGNY9dSZAV50yT8ohZF/GKkfhZQ2ro0c0l6jWBlt87F6iJ7Q6brXKVZGW40miP7XbjuNYkX0zSc8vixp8gTLCFoc',
    'assets/blindboxchallenge/blockstates/diamond_pillow.json': 'eNqr5uVSUFAqSyzKTMwrKVayUqgGCQCFEEwgJzc/JTUHKKKUlJOZl5KUX5GckZiTk5qXnmqVlJOfnK2fkpmYm5+XEl+QmZOTX64E0VgLooBELS8XALNWHJw=',
    'assets/blindboxchallenge/blockstates/glow_stick.json': 'eNqr5uVSUFAqSyzKTMwrKVayUqgGCQCFEEwgJzc/JTUHKKKUlJOZl5KUX5GckZiTk5qXnmqVlJOfnK2fnpNfHl9ckpmcrQTRVAuigEQtLxcAMl8bAA==',
    'assets/blindboxchallenge/blockstates/glow_stick_wall.json': 'eNqr5uVSUFAqSyzKTMwrKVayUqgGCQCF0hKTM/PSbVMTi0sQokDx3PyU1BygiFJSTmZeSlJ+RXJGYk5Oal56qlVSTn5ytn56Tn55fHFJZnJ2fDlQRkkHrrUSqM3I3AAhUFoG0gEULSkqTYWI1uqg2p+XX1SSQU0HkGZ9cX4pda03tCDNAeWp1A1/SwLWgyggUcvLBQAIK5Sw',
    'assets/blindboxchallenge/blockstates/music_box.json': 'eNqr5uVSUFAqSyzKTMwrKVayUqgGCQCFEEwgJzc/JTUHKKKUlJOZl5KUX5GckZiTk5qXnmqVlJOfnK2fW1qcmRwPlFCC6KkFUUCilpcLABJfGpM=',
    'assets/blindboxchallenge/blockstates/safety_landing.json': 'eNqr5uVSUFAqSyzKTMwrKVayUqgGCQCFEEwgJzc/JTUHKKKUlJOZl5KUX5GckZiTk5qXnmqVlJOfnK1fnJiWWlIZn5OYl5KZl64E0VgLooBELS8XALM8HJI=',
    'assets/blindboxchallenge/blockstates/stone_pillow.json': 'eNqr5uVSUFAqSyzKTMwrKVayUqgGCQCFEEwgJzc/JTUHKKKUlJOZl5KUX5GckZiTk5qXnmqVlJOfnK1fXJKflxpfkJmTk1+uBNFWC6KARC0vFwB09hvp',
    'data/blindboxchallenge/loot_tables/blocks/anywhere_door.json': 'eNp9jsEOgjAMhu8kvMOyMxevvIoxZIwqjaUl20QI4d2FEUGi8bS/+76m/5gmSukwtKBzpRtksM5cQ16S2LvOIm1FyM/4vExKjeszAycUwSnbvoCDQ/iwDxtR+T6GARqdHSQ2TZRKQq5K6W1tiIBvkBsenjU4KCoRp/el6R0vexsrXGFA4b+FNuvYyj9chx34AvqWxC/817U1xHnOU5q8AIwVVFc=',
    'data/blindboxchallenge/loot_tables/blocks/bml_cheer_stick.json': 'eNp9jkEKgzAQRfeCdwhZu+nWq5QiJk7r0ElGklQs4t0bI9WGlq7yJ+8N8+eyEEKG5wCyFtKgBe3aa6gVsb7LKtGBmXzE53USYt6eCBxTAqdq/wIbHMKHnW0k5fsYBjCyyiTbmiQpQtspnnTfEoG9Qa0MNboHcI0PGDsea8s7Xo4+mm2HAdn+rbRbeS//cCOO4BuYBmK/8l/XtpDmmJeyeAFR81T/',
    'data/blindboxchallenge/loot_tables/blocks/bml_cheer_stick_wall.json': 'eNp9jkEKgzAQRfeCdwhZu+nWq5QiJk7r0ElGklQs4t0bI9WGlq7yJ+8N8+eyEEKG5wCyFtKgBe3aa6gVsb7LKtGBmXzE53USYt6eCBxTAqdq/wIbHMKHnW0k5fsYBjCyyiTbmiQpQtspnnTfEoG9Qa0MNboHcI0PGDsea8s7Xo4+mm2HAdn+rbRbeS//cCOO4BuYBmK/8l/XtpDmmJeyeAFR81T/',
    'data/blindboxchallenge/loot_tables/blocks/diamond_pillow.json': 'eNp9jkEOgjAQRfck3KHpmo1brmIMKWXUidNO01bEEO5uKREkGlf90/cm88eyEELGpwNZC2nQgvbqHOuWWN9klaljppDwcZ6EGJcnAc+UwaFav8BGj/Bh7zay8n0MIxhZ7SSrTJZaQtu1POirIgJ7gbpDZdh2jUMifshta3rH01ZHJxMjsv3baLX2tcLd99hDaGBwxGHmv64tIc8pT2XxAvMoVLM=',
    'data/blindboxchallenge/loot_tables/blocks/glow_stick.json': 'eNp9jsEOgjAMhu8kvMOyMxevvIoxBEbFxtKSbSKE8O6OEUGi8bS/+76m/5QmSmk/dqBzpVtkMLa8+rwiMXedRdqJkAv4vExKTesTgBWK4JRtX8DeInzYh42ofB9DD63ODhKXbZQqQq4rGcytJAJuIG9InoXzGOrtG/M7XvYqRrhGj8J/22zWsZJ72B57cAUMHYlb+K9ra4hzyHOavAA8VlMX',
    'data/blindboxchallenge/loot_tables/blocks/glow_stick_wall.json': 'eNp9jsEOgjAMhu8kvMOyMxevvIoxBEbFxtKSbSKE8O6OEUGi8bS/+76m/5QmSmk/dqBzpVtkMLa8+rwiMXedRdqJkAv4vExKTesTgBWK4JRtX8DeInzYh42ofB9DD63ODhKXbZQqQq4rGcytJAJuIG9InoXzGOrtG/M7XvYqRrhGj8J/22zWsZJ72B57cAUMHYlb+K9ra4hzyHOavAA8VlMX',
    'data/blindboxchallenge/loot_tables/blocks/music_box.json': 'eNp9jkELgzAMhe+C/6H07GVX/8oYojXbwtJE2ioO8b+vVqaTjZ3yku+F96Y8U0qHZwe6VNoig3H1NZQNiXnoItFOhHzE52VTalpHBE4ogVOxnYCDQ/hwHz6S5TsMA1hdHExc22RqCLltZDT3mgj4BqXtPZoqnvT+ML/lZW9ihFsMKPy3zOY6NvK9G3AAX8HYkfiF/0pbRdqjnvPsBcvIUqo=',
    'data/blindboxchallenge/loot_tables/blocks/safety_landing.json': 'eNp9jkEKgzAQRfeCdwhZu+nWq5QiMY42dJyRJBVFvHtjpNrQ0lX+5L1h/pJnQkg/DyBLIXtDoK1qfVkj64csIh2Y0QV83SYhlv0JwDJGcCmOLyBvDXzYyUZUvo8ZD70sEolUH6UaDTU1T/quEIE6KJ1qwc8VKmoMdfLcWt/xdtbRHCxvmP42Oqy0lnva0YzgKpgGZLfxX9f2EOeQ1zx7Ae36VKk=',
    'data/blindboxchallenge/loot_tables/blocks/stone_pillow.json': 'eNp9jsEOgjAMhu8kvMOyMxevvIoxBEbVxq5dtokYwrsLI4JE42l/931N/yHPlNLx6UCXSltkML4+x7IhMTddJOpEKEz4OE9KDcszAS+UwKFYv4CjR/iwdxtJ+T6GEawudhLXNkkNIbeN9OZaEwFfoAxRGCqHRPLQ2874jqetjBFuMaLw3z6rtS8V7r7DDkIFvSMJM/91bQlpnvKYZy8nmFQA',
}


def decode_authoritative_json(relative: str) -> bytes:
    """Decode embedded JSON bytes without reading workspace resources."""
    return zlib.decompress(base64.b64decode(AUTHORITATIVE_JSON_PAYLOADS[relative], validate=True))
